### ISSUE TITLE
populate table whit json

### ISSUE THREAD

**Issue by chrystiansweick** [toni-heittola/js-datatable#3]
hello, i'm chrystian sweick,
I'm implementing your "js-datatable" component and I'm having trouble popping it with json.
can I only implement JSON per file? or can I implement it by javaScript?

**Comment by toni-heittola** [comment]
Hi,

You can populate the table from JSON, see example here > https://toni-heittola.github.io/js-datatable/#simple-dynamic-table-from-json 

If you are developing locally, make sure you are using local web server since you cannot access local JSON files from browser.
